"use client";

import React, { forwardRef } from 'react';
import { Section, Question, ExamMeta } from '@/types';
import { formatSerial, toBengali } from '@/utils/helpers';
import { BlockRenderer } from './question-editor/BlockRenderer';

interface PrintablePaperProps {
    examMeta: ExamMeta;
    sections: Section[];
    questions: Question[];
}

export const PrintablePaper = forwardRef<HTMLDivElement, PrintablePaperProps>(({ examMeta, sections, questions }, ref) => {
    return (
        <div ref={ref} className="bg-white p-12 w-[210mm] min-h-[297mm] mx-auto text-black">
            {/* Header */}
            <div className="text-center mb-8 border-b-2 border-gray-800 pb-4">
                <h1 className="text-3xl font-bold mb-2">{examMeta.schoolName}</h1>
                <div className="flex justify-between items-end mt-4 font-bold text-lg border-t border-gray-400 pt-2">
                    <span>{examMeta.examType}</span>
                    <span>{examMeta.examName}</span>
                </div>
                <div className="flex justify-between mt-2 text-md font-semibold">
                    <span>Time: {examMeta.time}</span>
                    <span>Full Marks: {toBengali(examMeta.declaredTotalMarks)}</span>
                </div>
            </div>

            {/* Sections */}
            <div className="space-y-8">
                {sections.map((section, sIdx) => {
                    const sectionQuestions = questions.filter(q => q.sectionId === section.id);
                    if (sectionQuestions.length === 0) return null;

                    return (
                        <div key={section.id}>
                            <div className="flex justify-between items-baseline font-bold mb-3">
                                <h3 className="text-lg underline decoration-gray-400 underline-offset-4">{section.title}</h3>
                                <span className="text-sm border border-gray-800 px-2 py-1 rounded">
                                    {toBengali(section.marksPerQuestion)} &#215; {toBengali(section.questionsToAttempt)} = {toBengali(section.marksPerQuestion * section.questionsToAttempt)}
                                </span>
                            </div>
                            <div className="space-y-6">
                                {sectionQuestions.map((q, qIdx) => (
                                    <div key={q.id} className="flex gap-3">
                                        <span className="font-bold min-w-[24px]">
                                            {formatSerial(qIdx, section.numberingStyle)}.
                                        </span>
                                        <div className="flex-1">
                                            {q.blocks && q.blocks.length > 0 ? (
                                                q.blocks.map(b => <BlockRenderer key={b.id} block={b} />)
                                            ) : (
                                                <p className="whitespace-pre-wrap">{q.title}</p>
                                            )}
                                        </div>
                                        <span className="font-semibold text-sm w-8 text-right">
                                            {toBengali(q.marks)}
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    );
                })}
            </div>

            {/* Footer */}
            <div className="mt-12 pt-4 border-t text-center text-xs text-gray-400">
                <p>Generated by ExamBuilder</p>
            </div>
        </div>
    );
});

PrintablePaper.displayName = "PrintablePaper";
